/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Controller.PeliculaController;
import Model.Pelicula;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class VendedorPelicula extends javax.swing.JDialog {

    private DefaultTableModel modelo = new DefaultTableModel();
    private PeliculaController peliculaController = new PeliculaController();
    private static int Opc = 1;
    SimpleDateFormat frmt = new SimpleDateFormat("dd/MM/yyyy");

    /**
     * Creates new form VendedorPelicula
     */
    public VendedorPelicula(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setLocationRelativeTo(null);
        tablePelicula.setModel(modelo);

        modelo.addColumn("ID");
        modelo.addColumn("Titulo");
        modelo.addColumn("Categoría");
        modelo.addColumn("Fecha");
        modelo.addColumn("Duración");
        modelo.addColumn("Idioma");

        /*
        modeloC.setHorizontalAlignment(SwingConstants.CENTER);
        tableUsuario.getColumnModel().getColumn(0).setCellRenderer(modeloC);
        tableUsuario.getColumnModel().getColumn(1).setCellRenderer(modeloC);
         */
        CargarDatosT();

        Botones(false, true, false, false, false);
        Escribir(false);
        txtPeliculaId.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        txtPeliculaId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnRetroceder = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtIdioma = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        tablePelicula = new javax.swing.JTable();
        txtDuracion = new javax.swing.JTextField();
        txtFecha = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnNuevo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setMaximumSize(null);
        btnNuevo.setMinimumSize(null);
        btnNuevo.setPreferredSize(new java.awt.Dimension(91, 27));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setMaximumSize(null);
        btnEditar.setMinimumSize(null);
        btnEditar.setPreferredSize(new java.awt.Dimension(91, 27));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        txtPeliculaId.setEditable(false);
        txtPeliculaId.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtPeliculaId.setText("0");
        txtPeliculaId.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Titulo :");

        btnRetroceder.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnRetroceder.setText("RETROCEDER");
        btnRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setMaximumSize(new java.awt.Dimension(0, 0));
        btnEliminar.setMinimumSize(null);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtIdioma.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        txtTitulo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        btnCancelar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setMaximumSize(null);
        btnCancelar.setMinimumSize(null);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Idioma :");

        txtCategoria.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCategoria.setPreferredSize(new java.awt.Dimension(10, 25));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Categoría :");

        btnGuardar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setMaximumSize(new java.awt.Dimension(0, 0));
        btnGuardar.setMinimumSize(new java.awt.Dimension(0, 0));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Duración :");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Fecha :");

        scroll.setBorder(null);

        tablePelicula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePelicula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePeliculaMouseClicked(evt);
            }
        });
        tablePelicula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablePeliculaKeyReleased(evt);
            }
        });
        scroll.setViewportView(tablePelicula);

        txtDuracion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        txtFecha.setDateFormatString("dd/MM/yyyy");
        txtFecha.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRetroceder)
                        .addGap(53, 53, 53)
                        .addComponent(txtPeliculaId, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4)
                            .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4)
                            .addComponent(txtIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(4, 4, 4)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRetroceder)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtPeliculaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        Opc = 1;
        Limpiar();
        Botones(true, false, false, false, true);
        Escribir(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        Opc = 2;
        Botones(true, false, false, false, true);
        Escribir(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnRetrocederActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int OPregunta = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea eliminar este Cliente?", ".: Sistema", JOptionPane.YES_NO_OPTION);
        if (OPregunta == JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(txtPeliculaId.getText());
            peliculaController.delete(id);
            MsgInformation("Pelicula Eliminada con exito!");
            Recarga();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        Limpiar();
        Botones(false, true, false, false, false);
        Escribir(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (Validar()) {

            String Mensaje = "";
            int id = Integer.parseInt(txtPeliculaId.getText());
            String Titulo = txtTitulo.getText();
            String Categoria = txtCategoria.getText();
            Date Fecha = txtFecha.getDate();
            String Duracion = txtDuracion.getText();
            String Idioma = txtIdioma.getText();
            Pelicula pelicula = new Pelicula(id, Titulo, Categoria, Fecha, Duracion, Idioma);
            if (Opc == 1) {
                peliculaController.insert(pelicula);
                Mensaje = "Nueva pelicula registrada exitosamente";
            } else {
                peliculaController.update(pelicula);
                Mensaje = "La pelicula ha sido actualziada";
            }
            MsgInformation(Mensaje);
            Recarga();

        } else {
            MsgError("Se encontraron datos vacios o invalidos");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tablePeliculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePeliculaMouseClicked
        // TODO add your handling code here:
        PasarDatosT();
    }//GEN-LAST:event_tablePeliculaMouseClicked

    private void tablePeliculaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablePeliculaKeyReleased
        // TODO add your handling code here:
        PasarDatosT();
    }//GEN-LAST:event_tablePeliculaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendedorPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendedorPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendedorPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendedorPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VendedorPelicula dialog = new VendedorPelicula(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRetroceder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable tablePelicula;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtDuracion;
    private com.toedter.calendar.JDateChooser txtFecha;
    private javax.swing.JTextField txtIdioma;
    private javax.swing.JTextField txtPeliculaId;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables

    public void CargarDatosT() {
        for (int i = 0; i < tablePelicula.getRowCount(); i++) {
            modelo.removeRow(i);
            i -= 1;
        }
        for (Pelicula peliculaT : peliculaController.findAll()) {
            modelo.addRow(new Object[]{
                peliculaT.getCodigo(),
                peliculaT.getTitulo(),
                peliculaT.getCategoria(),
                frmt.format(peliculaT.getFecha()),
                peliculaT.getDuracion(),
                peliculaT.getIdioma(),});
        }
        Color fondo = new Color(102, 102, 102);
        scroll.getViewport().setBackground(fondo);
    }

    public boolean Validar() {
        boolean respuesta = false;
        if (txtTitulo.getText().isEmpty()) {
            respuesta = false;
        } else if (txtCategoria.getText().isEmpty()) {
            respuesta = false;
        } else if (txtDuracion.getText().isEmpty()) {
            respuesta = false;
        } else if (txtIdioma.getText().isEmpty()) {
            respuesta = false;
        } else {
            respuesta = true;
        }
        return respuesta;
    }

    public void Limpiar() {
        txtPeliculaId.setText("1");
        txtTitulo.setText(null);
        txtCategoria.setText(null);
        txtFecha.setDate(null);
        txtDuracion.setText(null);
        txtIdioma.setText(null);
    }

    public void Botones(boolean Guardar, boolean Nuevo, boolean Editar, boolean Eliminar, boolean Cancelar) {
        btnGuardar.setEnabled(Guardar);
        btnNuevo.setEnabled(Nuevo);
        btnEditar.setEnabled(Editar);
        btnEliminar.setEnabled(Eliminar);
        btnCancelar.setEnabled(Cancelar);
    }

    public void Escribir(boolean status) {
        txtTitulo.setEditable(status);
        txtCategoria.setEditable(status);
        txtFecha.setEnabled(status);
        txtDuracion.setEditable(status);
        txtIdioma.setEditable(status);

    }

    public void PasarDatosT() {
        int pos = tablePelicula.getSelectedRow();

        txtPeliculaId.setText(tablePelicula.getValueAt(pos, 0).toString());
        txtTitulo.setText(tablePelicula.getValueAt(pos, 1).toString());
        txtCategoria.setText(tablePelicula.getValueAt(pos, 2).toString());
        try {
            Date fecha = frmt.parse(tablePelicula.getValueAt(pos, 3).toString());
            txtFecha.setDate(fecha);
        } catch (ParseException ex) {
            Logger.getLogger(VendedorPelicula.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtDuracion.setText(tablePelicula.getValueAt(pos, 4).toString());
        txtIdioma.setText(tablePelicula.getValueAt(pos, 5).toString());
        Botones(false, true, true, true, false);
        Escribir(false);
    }

    public void Recarga() {
        CargarDatosT();
        Limpiar();
        Escribir(false);
        Botones(false, true, false, false, false);
    }

    private void MsgError(String Mensaje) {
        JOptionPane.showMessageDialog(null, Mensaje, ".: Sistema", JOptionPane.ERROR_MESSAGE);
    }

    private void MsgInformation(String Mensaje) {
        JOptionPane.showMessageDialog(null, Mensaje, ".: Sistema", JOptionPane.INFORMATION_MESSAGE);
    }
}
